### ISSUE TITLE
Cannot be installed on Ubuntu 16.04

### ISSUE THREAD

**Issue by happytomy** [wolfgangw/digital_cinema_tools_distribution#30]
Today I install Ubuntu 16.04 then use wget http://git.io/digital-cinema-tools-setup && bash digital-cinema-tools-setup to install the package.But after input the command line on terminal then I get denied.

**Comment by egoglobal** [comment]
The error I'm getting is:
"Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source"
The package is now libpng12-0

Modified the installation script but dcp_inspect is still not working.

**Comment by brocky27** [comment]
@happytomy did you try sudo at the start? @egoglobal me too!

**Comment by carlschuurbiers** [comment]
I have the same problem with Ubuntu 17.04 Zesty Zapus:

```
Hit:1 http://archive.canonical.com/ubuntu zesty InRelease
Hit:2 http://security.ubuntu.com/ubuntu zesty-security InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu zesty InRelease
Hit:4 http://de.archive.ubuntu.com/ubuntu zesty-updates InRelease
Hit:5 http://de.archive.ubuntu.com/ubuntu zesty-backports InRelease
Reading package lists... Done                      
digital-cinema-tools-setup: Package preparation OK
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libtiff5-dev' instead of 'libtiff-dev'
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng12-dev' has no installation candidate
apt-get: Failed to install basic requirements

```

any ideas?

**Comment by carlschuurbiers** [comment]
opened a new issue for this with clearer title.

**Comment by utekardeepak** [comment]
plz help
--2017-11-21 21:32:42--  https://git.io/digital-cinema-tools-setup
Resolving git.io (git.io)... 50.17.206.192, 50.19.217.10, 23.23.241.244, ...
Connecting to git.io (git.io)|50.17.206.192|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/wolfgangw/digital_cinema_tools_distribution/master/digital-cinema-tools-setup [following]
--2017-11-21 21:32:44--  https://raw.github.com/wolfgangw/digital_cinema_tools_distribution/master/digital-cinema-tools-setup
Resolving raw.github.com (raw.github.com)... 151.101.36.133
Connecting to raw.github.com (raw.github.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/wolfgangw/digital_cinema_tools_distribution/master/digital-cinema-tools-setup [following]
--2017-11-21 21:32:45--  https://raw.githubusercontent.com/wolfgangw/digital_cinema_tools_distribution/master/digital-cinema-tools-setup
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28673 (28K) [text/plain]
Saving to: ‘digital-cinema-tools-setup’

digital-cinema-tool 100%[===================>]  28.00K   147KB/s    in 0.2s    

2017-11-21 21:32:46 (147 KB/s) - ‘digital-cinema-tools-setup’ saved [28673/28673]

digital-cinema-tools-setup v1.2015.02.20
OS: ubuntu
build-essential: OK
curl: OK
libxslt1-dev: OK
libxml2-dev: OK
libexpat1-dev: OK
xmlsec1: OK
libreadline-dev: OK
zlib1g: OK
zlib1g-dev: OK
libssl-dev: OK
imagemagick: OK
mplayer: OK
sox: OK
git-core: OK
libtiff-dev: Installation required
libpng12-dev: OK

digital-cinema-tools-setup: 1 packages missing
digital-cinema-tools-setup: libtiff-dev

Please enter your password
[sudo] password for deepak: 
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://in.archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease             
Get:4 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]  
Fetched 204 kB in 1s (148 kB/s)                                    
Reading package lists... Done
digital-cinema-tools-setup: Package preparation OK
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libtiff5-dev' instead of 'libtiff-dev'
libtiff5-dev is already the newest version (4.0.6-1ubuntu0.2).
0 upgraded, 0 newly installed, 0 to remove and 237 not upgraded.
apt-get: OK
source $HOME/.bash_profile
bashrc: OK
PATH: /home/deepak/.digital_cinema_tools/.bin available in PATH
rbenv: OK
gem: --no-ri --no-rdoc
gemrc: OK
Already up-to-date.
ruby-build: OK
Ruby: OK
Nokogiri: Found installed gem
Nokogiri: C14N support present
Nokogiri: OK
openjpeg: Installing ...
openjpeg: Downloading tarball http://openjpeg.googlecode.com/files/openjpeg-1.5.0.tar.gz
--2017-11-21 21:32:58--  http://openjpeg.googlecode.com/files/openjpeg-1.5.0.tar.gz
Resolving openjpeg.googlecode.com (openjpeg.googlecode.com)... 74.125.68.82, 2404:6800:4003:c02::52
Connecting to openjpeg.googlecode.com (openjpeg.googlecode.com)|74.125.68.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-21 21:32:58 ERROR 404: Not Found.

PING googlecode.l.googleusercontent.com (74.125.68.82) 56(84) bytes of data.
64 bytes from sc-in-f82.1e100.net (74.125.68.82): icmp_seq=1 ttl=47 time=84.1 ms

--- googlecode.l.googleusercontent.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 84.135/84.135/84.135/0.000 ms
openjpeg: Failed to download tarball. Try again later
tar (child): openjpeg-1.5.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Failed to extract tarball at /home/deepak/.digital_cinema_tools/.lib/openjpeg
asdcplib: Installing 1.12.58 ...
asdcplib: Downloading tarball http://download.cinecert.com/asdcplib/asdcplib-1.12.58.tar.gz
--2017-11-21 21:32:58--  http://download.cinecert.com/asdcplib/asdcplib-1.12.58.tar.gz
Resolving download.cinecert.com (download.cinecert.com)... 207.151.82.243
Connecting to download.cinecert.com (download.cinecert.com)|207.151.82.243|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.cinecert.com/asdcplib/asdcplib-1.12.58.tar.gz [following]
--2017-11-21 21:32:59--  https://download.cinecert.com/asdcplib/asdcplib-1.12.58.tar.gz
Connecting to download.cinecert.com (download.cinecert.com)|207.151.82.243|:443... connected.
ERROR: cannot verify download.cinecert.com's certificate, issued by ‘emailAddress=hostmaster@cinecert.com,CN=CineCert Network Services CA2,OU=Network Services,O=CineCert\\, LLC,L=Burbank,ST=California,C=US’:
  Unable to locally verify the issuer's authority.
To connect to download.cinecert.com insecurely, use `--no-check-certificate'.
ping: unknown host download.cinecert.com/asdcplib
asdcplib: download.cinecert.com/asdcplib seems to be down
asdcplib: Failed to download tarball. Try again later
tar (child): asdcplib-1.12.58.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
asdcplib: Failed to extract tarball at /home/deepak/.digital_cinema_tools/.lib/asdcplib
Digital cinema tools distribution: Pulling updates ...
Already up-to-date.
Digital cinema tools distribution: certificate_thumbprint.rb OK
Digital cinema tools distribution: cinemaslides OK
Digital cinema tools distribution: db_adjust_for_dolby_fader_ref.rb OK
Digital cinema tools distribution: dc_crypto_context.rb OK
Digital cinema tools distribution: dcp_inspect OK
Digital cinema tools distribution: kdm-decrypt.rb OK
Digital cinema tools distribution: make-dc-certificate-chain.rb OK
Digital cinema tools distribution: public_key_thumbprint.rb OK
Digital cinema tools distribution: signature_check.rb OK
Digital cinema tools distribution: x509_extract.rb OK
Digital cinema tools distribution: x509_inspect.rb OK
Digital cinema tools distribution: xsd-check.rb OK
Digital cinema tools distribution: Replacing setup with repo version
dcp_inspect: Nice-to-have gem ttfunk OK
cinemaslides: Required gem highline OK
cinemaslides: CINEMASLIDESDIR is set. OK
cinemaslides: CINEMACERTSTORE is set. OK
Local certificate store: Required certificates found
Local certificate store: Failed to find valid certificate chain in /home/deepak/.digital_cinema_tools/CERTSTORE
set show-all-if-ambiguous on
Tab completion: Fastpath set to on. Leaving untouched. OK
digital-cinema-tools-setup: OK
digital-cinema-tools-setup: Removing ad-hoc self

There were errors:
Error: openjpeg: Failed to download tarball. Try again later
Error: Failed to extract tarball at /home/deepak/.digital_cinema_tools/.lib/openjpeg
Error: asdcplib: download.cinecert.com/asdcplib seems to be down
Error: asdcplib: Failed to download tarball. Try again later
Error: asdcplib: Failed to extract tarball at /home/deepak/.digital_cinema_tools/.lib/asdcplib

digital-cinema-tools-setup: Done

**Comment by wolfgangw** [comment]
Considered fixed with 39498769436e080c71d4eb4eaf04038b3d07f846.

Please remove the installer script and run ```wget http://git.io/digital-cinema-tools-setup && bash digital-cinema-tools-setup``` again.

**Comment by brocky27** [comment]
I'm still having issues with this on Ubuntu 14.04, do I need to install add an old source?
