### ISSUE TITLE
Ubuntu 18.04 installation

### ISSUE THREAD

**Issue by ddmar** [wolfgangw/digital_cinema_tools_distribution#38]
Hi Wolfgang,

I'm trying to install digital cinema tools on Ubuntu 18.04, unfortunately the script didn't work:

```
dcp_inspect
Required command asdcp-info not found. Please run digital-cinema-tools-setup or install the missing component manually
Required command asdcp-unwrap not found. Please run digital-cinema-tools-setup or install the missing component manually
Required command kmuuidgen not found. Please run digital-cinema-tools-setup or install the missing component manually
```

I've managed to install asdcplib manually (developement version - **asdcplib-2.8.29** - stable one didn't work) but it's still not enough.

Any chance you might be able to advise? I'd really appreciate it!

```
NoMethodError: undefined method `map' for nil:NilClass /home/nefs/.digital_cinema_tools/.bin/dcp_inspect:398:in `asdcplib_version'
/home/nefs/.digital_cinema_tools/.bin/dcp_inspect:4740:in <main>

Sorry, dcp_inspect v1.2018.07.30 crashed
Please get in touch to help fix it
See https://github.com/wolfgangw
Your feedback is much appreciated. Thanks in advance
```

thanks!
M.

**Comment by wolfgangw** [comment]
eb9eeefcad3967cb05bf72f8409b0c85a7a8d2fe should fix this one.

**Comment by choopakenvrac** [comment]
Hello there,
I still have the issue on Ubuntu Linux 18.04.3 LTS.

Best regards

**Comment by choopakenvrac** [comment]
see last line below:

Already up to date.
ruby-build: OK
Ruby: OK
Nokogiri: Found installed gem
Nokogiri: C14N support present
Nokogiri: OK
asdcplib: OK (2.10.31)
Digital cinema tools distribution: Pulling updates ...
Already up to date.
Digital cinema tools distribution: certificate_thumbprint.rb OK
Digital cinema tools distribution: db_adjust_for_dolby_fader_ref.rb OK
Digital cinema tools distribution: dc_crypto_context.rb OK
Digital cinema tools distribution: dcp_inspect OK
Digital cinema tools distribution: kdm-decrypt.rb OK
Digital cinema tools distribution: make-dc-certificate-chain.rb OK
Digital cinema tools distribution: public_key_thumbprint.rb OK
Digital cinema tools distribution: signature_check.rb OK
Digital cinema tools distribution: x509_extract.rb OK
Digital cinema tools distribution: x509_inspect.rb OK
Digital cinema tools distribution: xsd-check.rb OK
Digital cinema tools distribution: digital-cinema-tools-setup OK
dcp_inspect: Nice-to-have gem ttfunk OK
cinemaslides: Required gem highline OK
set show-all-if-ambiguous on
Tab completion: Fastpath set to on. Leaving untouched. OK
digital-cinema-tools-setup: OK

There were errors:
Error: digital-cinema-tools-setup: Failed to prepare package installation

digital-cinema-tools-setup: Done

**Comment by wolfgangw** [comment]
@ddmar @choopakenvrac considered fixed.

If you can, remove your `~/.digital_cinema_tools` directory and run
```
wget https://git.io/digital-cinema-tools-setup && bash digital-cinema-tools-setup
```
for a clean initial setup.

**Comment by ddmar** [comment]
Thanks Wolfgang, it seems to work!

Have a great New Year!


pt., 29 gru 2023 o 05:46 Wolfgang Woehl ***@***.***>
napisał(a):

**Comment by wolfgangw** [comment]
Nice, thanks for the feedback.
